name: process

on:
  workflow_dispatch

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: npm install 

    - name: Benchmark
      run: npm run process