name: Process

on:
  workflow_dispatch:
    inputs:
      limit:
        description: Limit
        required: true
        default: '100'
      runKey:
        description: Run Key
        required: false

jobs:
  process:
    runs-on: ubuntu-latest
    env:
      LIMIT: ${{ github.event.inputs.limit }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Check environment
      run: echo $LIMIT

    - name: Install Dependencies
      run: npm install 

    - name: Benchmark
      run: npm run process

    - name: Save results
      uses: actions/upload-artifact@v1
      with:
        name: results
        path: output/results.csv