name: Process

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform (alexa, google, or siri)
        required: true
        default: 'alexa'
      limit:
        description: Limit
        required: true
        default: '100'
      runKey:
        description: Run Key
        required: false

jobs:
  process:
    runs-on: ubuntu-latest
    env:
      LIMIT: ${{ github.event.inputs.limit }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      PLATFORM: ${{ github.event.inputs.platform }} 
      RUN_KEY: ${{ github.event.inputs.runKey }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Check environment
      run: |
        echo 'Limit: ' $LIMIT
        echo 'MySQL: ' $MYSQL_HOST
        echo 'Platform: ' $PLATFORM
        echo 'Run Key: ' $RUN_KEY

    - name: Install Dependencies
      run: npm install 

    - name: Benchmark
      run: npm run process:${PLATFORM}

    - name: Save results
      uses: actions/upload-artifact@v1
      with:
        name: results
        path: output/results.csv